# Importing necessary libraries
from transformers import pipeline
import numpy as np
import librosa
import time
import os

# functions
def getFileNameAndExtension(file_path):
    """
    Description:
    -------------
    This function takes a file path as input and it will return the filename and extension for that file path
    
    Arguments:
    -------------
    file_path: Absolute or relative path for the input file
    
    Returns:
    -------------
    filename: name of the file
    extension: extension of file
    """
    # get the basename of the file from its absolute path
    basename = os.path.basename(file_path)
    # get the filename and file extension
    filename, ext = basename.split(".")
    return filename,ext

def segmentLargeArray(inputArray,array_length,chunksize=200000):
    """
    Description:
    -------------
    This function segments a large array into list of smaller arrays based on the chunk size input by user and returns the list of segments
    
    Arguments:
    -------------
    inputArray: Large array to be segmented
    array_length: Size of the input array
    chunksize: Length of an array segment
    
    Returns:
    -------------
    list_of_segments: List of segments each of length chunksize
    """
    list_of_segments = []
    for i in range(0,array_length+1,chunksize):
        list_of_segments.append(inputArray[i:i+chunksize])
    return list_of_segments 

def generateTranscript(audio_input,model):
    """
    Description:
    -------------
    This function generates Nepali transcript for the Nepali speech input
    
    Arguments:
    -------------
    audio_input: Path of audio file for which transcript is generated
    model: pretrained ASR model to perform speech recognition
    
    Returns:
    -------------
    output: Nepali text transcript for the given audio input
    """
    # set mono=True as the SpeechRecognitionPipelince can only work with mono audio, Also sampling rate is set to 16k as the model was trained at this sampling rate
    speech_array, sr = librosa.load(audio_input,mono=True,sr=16000)
    array_length = speech_array.shape[0]
    # for longer audio, segmentation needs to be done to prevent program from consuming entire RAM which may cause error, so I am diving the entire audio to smaller segments and will process these segments
    if array_length > 250000:
        list_of_segments = segmentLargeArray(speech_array,array_length, 200000)
        output = ''
        for segment in list_of_segments:
            output += model(segment)["text"]
    else:
        output = model(audio_input)["text"]
    return output

def writeOutputToFile(output, audio_file_path):
    """
    Description:
    -------------
    This function writes the generated Nepali transcript to a file inside the output folder
    
    Arguments:
    -------------
    output: Nepali text transcript generated by ASR model
    audio_file_path: File path of the input audio
    
    Returns:
    -------------
    destination_file_path: File path of the text transcript
    """
    filename,ext = getFileNameAndExtension(audio_file_path)
    destination_file_path = f"./output_folder/{filename}.txt"
    with open(destination_file_path,"w",encoding="utf-8") as f:
        f.write(output)
    return destination_file_path

def generateTranscriptForFolder(input_folder_path,model):
    """
    Description:
    -------------
    This function generates transcript for all the audio files inside an input folder 
    
    Arguments:
    -------------
    input_folder_path: Path to the folder that contains Nepali audio files
    model: Pretrained ASR model to generate transcript
    
    Returns:
    -------------
    None
    """
    available_files = os.listdir(input_folder_path)
    audio_extensions = ['mp3','wav','flac']
    print(f"There are total {len(audio_extensions)} files in {input_folder_path}")
    for available_file in available_files:
        filename, ext = getFileNameAndExtension(available_file)
        if ext in audio_extensions:
            print(f"{available_file} is a valid audio file, so proceeding to generate the transcript")
            audio_file_path = f"{input_folder_path}/{available_file}"
            start_time = time.time()
            output = generateTranscript(audio_file_path,model)
            print(f"Transcript generated at {time.time() - start_time} seconds for {available_file}")
            destination_file_path = writeOutputToFile(output,audio_file_path)
            print(f"Transcript for {available_file} is written at {destination_file_path}")
        else:
            print(f"{available_file} is not a valid audio file, so moving to next file")

def generateTranscriptForFile(input_file_path,model):
    """
    Description:
    -------------
    This function generates transcript for a single audio file
    
    Arguments:
    -------------
    input_file_path: Path to the input audio file
    model: Pretrained ASR model to generate transcript
    
    Returns:
    -------------
    None
    """
    audio_extensions = ['mp3','wav','flac']
    filename, ext = getFileNameAndExtension(input_file_path)
    if ext in audio_extensions:
        print(f"{input_file_path} is a valid audio file, so proceeding to generate transcript")
        start_time = time.time()
        output = generateTranscript(input_file_path,model)
        print(f"Transcript generated in {time.time() - start_time} seconds for {filename}")
        destination_file_path = writeOutputToFile(output,input_file_path)
        print(f"Transcript for {filename} is written at {destination_file_path}")
    else:
        print(f"{input_file_path} is not a valid audio file, please enter a valid audio file with extension mp3, wav or flac")

def main(key="folder"):
    """
    Description:
    -------------
    Main function for Nepali Audio to Nepali text
    
    Arguments:
    -------------
    key: This determines whether to generate transcript for a file or a folder. 
        1. Default "folder" to generate transcript for all files inside a folder
        2. "file": to generate transcript for a single file
    
    Returns:
    -------------
    None
    """
    try:
        print("Loading Model from Huggingface")
        # loading the model from huggingface
        trained_model = pipeline("automatic-speech-recognition","anish-shilpakar/wav2vec2-nepali")
        print("Model loaded successfully")
    except Exception as e:
        print(f"Failed to load the model. Following error occured:\n{e}")
    
    try:
        # get the key from user
        key = input("Choose Option:\n1 for Folder Input and 2 for File option\n=> ")
        if key == '1':
            input_folder_path = input("Enter the path for the folder which contains audio files: ")
            generateTranscriptForFolder(input_folder_path,trained_model)
        elif key == '2':
            input_file_path = input("Enter the path for the audio file: ")
            generateTranscriptForFile(input_file_path,trained_model)
        else:
            print(f"{key} is not a valid input")
        print("Program run completed")
    except Exception as e:
        print(f"Failed to generate transcripts. Following error occured:\n{e}")
        

if __name__ == "__main__":
    main()